//Auto Generated by 'npm run gen-icon-index'
import { exportToGlobal } from '../../../utils/utils';

import ArrowRight from './arrow-right';
import Backward from './backward';
import Bars from './bars';
import Book from './book';
import Check from './check';
import CircleCheck from './circle-check';
import CircleCross from './circle-cross';
import CircleExclamation from './circle-exclamation';
import Close from './close';
import Cog from './cog';
import Cogs from './cogs';
import Copy from './copy';
import Download from './download';
import Edit from './edit';
import EllipsisH from './ellipsis-h';
import EllipsisV from './ellipsis-v';
import Exchange from './exchange';
import Exclamation from './exclamation';
import Eye from './eye';
import EyeClose from './eye-close';
import FastBackward from './fast-backward';
import FastForward from './fast-forward';
import File from './file';
import FloppyDisk from './floppy-disk';
import Folder from './folder';
import Forward from './forward';
import List from './list';
import Loading from './loading';
import Logout from './logout';
import Minus from './minus';
import MousePointer from './mouse-pointer';
import Move from './move';
import OpenFolder from './open-folder';
import Paste from './paste';
import Pause from './pause';
import Plus from './plus';
import Question from './question';
import Redo from './redo';
import Refresh from './refresh';
import Search from './search';
import Share from './share';
import Share2 from './share2';
import ShopCart from './shop-cart';
import Square from './square';
import ThreeDots from './three-dots';
import Trash from './trash';
import Triangle from './triangle';
import Undo from './undo';
import ZoomIn from './zoom-in';
import ZoomOut from './zoom-out';
const builtinIcons: Record<string, string | string[]> = {
  "arrow-right": ArrowRight,
  "backward": Backward,
  "bars": Bars,
  "book": Book,
  "check": Check,
  "circle-check": CircleCheck,
  "circle-cross": CircleCross,
  "circle-exclamation": CircleExclamation,
  "close": Close,
  "cog": Cog,
  "cogs": Cogs,
  "copy": Copy,
  "download": Download,
  "edit": Edit,
  "ellipsis-h": EllipsisH,
  "ellipsis-v": EllipsisV,
  "exchange": Exchange,
  "exclamation": Exclamation,
  "eye": Eye,
  "eye-close": EyeClose,
  "fast-backward": FastBackward,
  "fast-forward": FastForward,
  "file": File,
  "floppy-disk": FloppyDisk,
  "folder": Folder,
  "forward": Forward,
  "list": List,
  "loading": Loading,
  "logout": Logout,
  "minus": Minus,
  "mouse-pointer": MousePointer,
  "move": Move,
  "open-folder": OpenFolder,
  "paste": Paste,
  "pause": Pause,
  "plus": Plus,
  "question": Question,
  "redo": Redo,
  "refresh": Refresh,
  "search": Search,
  "share": Share,
  "share2": Share2,
  "shop-cart": ShopCart,
  "square": Square,
  "three-dots": ThreeDots,
  "trash": Trash,
  "triangle": Triangle,
  "undo": Undo,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
};
export default builtinIcons;
exportToGlobal('icons', {
  get() {
    return ["arrow-right","backward","bars","book","check","circle-check","circle-cross","circle-exclamation","close","cog","cogs","copy","download","edit","ellipsis-h","ellipsis-v","exchange","exclamation","eye","eye-close","fast-backward","fast-forward","file","floppy-disk","folder","forward","list","loading","logout","minus","mouse-pointer","move","open-folder","paste","pause","plus","question","redo","refresh","search","share","share2","shop-cart","square","three-dots","trash","triangle","undo","zoom-in","zoom-out"]
  }
})
// for Demo
/*
  <az-icon icon="arrow-right" title="arrow-right"></az-icon>
  <az-icon icon="backward" title="backward"></az-icon>
  <az-icon icon="bars" title="bars"></az-icon>
  <az-icon icon="book" title="book"></az-icon>
  <az-icon icon="check" title="check"></az-icon>
  <az-icon icon="circle-check" title="circle-check"></az-icon>
  <az-icon icon="circle-cross" title="circle-cross"></az-icon>
  <az-icon icon="circle-exclamation" title="circle-exclamation"></az-icon>
  <az-icon icon="close" title="close"></az-icon>
  <az-icon icon="cog" title="cog"></az-icon>
  <az-icon icon="cogs" title="cogs"></az-icon>
  <az-icon icon="copy" title="copy"></az-icon>
  <az-icon icon="download" title="download"></az-icon>
  <az-icon icon="edit" title="edit"></az-icon>
  <az-icon icon="ellipsis-h" title="ellipsis-h"></az-icon>
  <az-icon icon="ellipsis-v" title="ellipsis-v"></az-icon>
  <az-icon icon="exchange" title="exchange"></az-icon>
  <az-icon icon="exclamation" title="exclamation"></az-icon>
  <az-icon icon="eye" title="eye"></az-icon>
  <az-icon icon="eye-close" title="eye-close"></az-icon>
  <az-icon icon="fast-backward" title="fast-backward"></az-icon>
  <az-icon icon="fast-forward" title="fast-forward"></az-icon>
  <az-icon icon="file" title="file"></az-icon>
  <az-icon icon="floppy-disk" title="floppy-disk"></az-icon>
  <az-icon icon="folder" title="folder"></az-icon>
  <az-icon icon="forward" title="forward"></az-icon>
  <az-icon icon="list" title="list"></az-icon>
  <az-icon icon="loading" title="loading"></az-icon>
  <az-icon icon="logout" title="logout"></az-icon>
  <az-icon icon="minus" title="minus"></az-icon>
  <az-icon icon="mouse-pointer" title="mouse-pointer"></az-icon>
  <az-icon icon="move" title="move"></az-icon>
  <az-icon icon="open-folder" title="open-folder"></az-icon>
  <az-icon icon="paste" title="paste"></az-icon>
  <az-icon icon="pause" title="pause"></az-icon>
  <az-icon icon="plus" title="plus"></az-icon>
  <az-icon icon="question" title="question"></az-icon>
  <az-icon icon="redo" title="redo"></az-icon>
  <az-icon icon="refresh" title="refresh"></az-icon>
  <az-icon icon="search" title="search"></az-icon>
  <az-icon icon="share" title="share"></az-icon>
  <az-icon icon="share2" title="share2"></az-icon>
  <az-icon icon="shop-cart" title="shop-cart"></az-icon>
  <az-icon icon="square" title="square"></az-icon>
  <az-icon icon="three-dots" title="three-dots"></az-icon>
  <az-icon icon="trash" title="trash"></az-icon>
  <az-icon icon="triangle" title="triangle"></az-icon>
  <az-icon icon="undo" title="undo"></az-icon>
  <az-icon icon="zoom-in" title="zoom-in"></az-icon>
  <az-icon icon="zoom-out" title="zoom-out"></az-icon>
*/
