//Auto Generated by 'npm run gen-icon-index'
import ArrowRight from './arrow-right';
import Check from './check';
import Close from './close';
import Download from './download';
import Minus from './minus';
import Move from './move';
import Plus from './plus';
import Redo from './redo';
import Refresh from './refresh';
import Undo from './undo';
const builtinIcons: Record<string, string> = {
  "arrow-right": ArrowRight,
  "check": Check,
  "close": Close,
  "download": Download,
  "minus": Minus,
  "move": Move,
  "plus": Plus,
  "redo": Redo,
  "refresh": Refresh,
  "undo": Undo,
};
export default builtinIcons;
// for Demo
/*
  <az-icon icon="arrow-right"></az-icon>
  <az-icon icon="check"></az-icon>
  <az-icon icon="close"></az-icon>
  <az-icon icon="download"></az-icon>
  <az-icon icon="minus"></az-icon>
  <az-icon icon="move"></az-icon>
  <az-icon icon="plus"></az-icon>
  <az-icon icon="redo"></az-icon>
  <az-icon icon="refresh"></az-icon>
  <az-icon icon="undo"></az-icon>
*/
