//Auto Generated by 'npm run gen-icon-index'
import ArrowRight from './arrow-right';
import Backward from './backward';
import Bars from './bars';
import Book from './book';
import Check from './check';
import Close from './close';
import Cog from './cog';
import Cogs from './cogs';
import Copy from './copy';
import Download from './download';
import EllipsisH from './ellipsis-h';
import EllipsisV from './ellipsis-v';
import Exchange from './exchange';
import FastBackward from './fast-backward';
import FastForward from './fast-forward';
import Forward from './forward';
import List from './list';
import Minus from './minus';
import MousePointer from './mouse-pointer';
import Move from './move';
import Pause from './pause';
import Plus from './plus';
import Redo from './redo';
import Refresh from './refresh';
import Search from './search';
import Square from './square';
import Triangle from './triangle';
import Undo from './undo';
import ZoomIn from './zoom-in';
import ZoomOut from './zoom-out';
const builtinIcons: Record<string, string> = {
  "arrow-right": ArrowRight,
  "backward": Backward,
  "bars": Bars,
  "book": Book,
  "check": Check,
  "close": Close,
  "cog": Cog,
  "cogs": Cogs,
  "copy": Copy,
  "download": Download,
  "ellipsis-h": EllipsisH,
  "ellipsis-v": EllipsisV,
  "exchange": Exchange,
  "fast-backward": FastBackward,
  "fast-forward": FastForward,
  "forward": Forward,
  "list": List,
  "minus": Minus,
  "mouse-pointer": MousePointer,
  "move": Move,
  "pause": Pause,
  "plus": Plus,
  "redo": Redo,
  "refresh": Refresh,
  "search": Search,
  "square": Square,
  "triangle": Triangle,
  "undo": Undo,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
};
export default builtinIcons;
// for Demo
/*
  <az-icon icon="arrow-right"></az-icon>
  <az-icon icon="backward"></az-icon>
  <az-icon icon="bars"></az-icon>
  <az-icon icon="book"></az-icon>
  <az-icon icon="check"></az-icon>
  <az-icon icon="close"></az-icon>
  <az-icon icon="cog"></az-icon>
  <az-icon icon="cogs"></az-icon>
  <az-icon icon="copy"></az-icon>
  <az-icon icon="download"></az-icon>
  <az-icon icon="ellipsis-h"></az-icon>
  <az-icon icon="ellipsis-v"></az-icon>
  <az-icon icon="exchange"></az-icon>
  <az-icon icon="fast-backward"></az-icon>
  <az-icon icon="fast-forward"></az-icon>
  <az-icon icon="forward"></az-icon>
  <az-icon icon="list"></az-icon>
  <az-icon icon="minus"></az-icon>
  <az-icon icon="mouse-pointer"></az-icon>
  <az-icon icon="move"></az-icon>
  <az-icon icon="pause"></az-icon>
  <az-icon icon="plus"></az-icon>
  <az-icon icon="redo"></az-icon>
  <az-icon icon="refresh"></az-icon>
  <az-icon icon="search"></az-icon>
  <az-icon icon="square"></az-icon>
  <az-icon icon="triangle"></az-icon>
  <az-icon icon="undo"></az-icon>
  <az-icon icon="zoom-in"></az-icon>
  <az-icon icon="zoom-out"></az-icon>
*/
