/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ComponentStyleType,
} from './global/typing';

export namespace Components {
  interface AzButton {
    /**
    * Button type
    */
    'type': ComponentStyleType;
  }
}

declare global {


  interface HTMLAzButtonElement extends Components.AzButton, HTMLStencilElement {}
  var HTMLAzButtonElement: {
    prototype: HTMLAzButtonElement;
    new (): HTMLAzButtonElement;
  };
  interface HTMLElementTagNameMap {
    'az-button': HTMLAzButtonElement;
  }
}

declare namespace LocalJSX {
  interface AzButton extends JSXBase.HTMLAttributes<HTMLAzButtonElement> {
    /**
    * Button type
    */
    'type'?: ComponentStyleType;
  }

  interface IntrinsicElements {
    'az-button': AzButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


